CatBoardInterface/Models/Comment.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections;

namespace CatBoardInterface.Models
{
  public class Comment
  {
    public string Body { get; set; }
    public string DateCreated { get; set; }
    public int Score { get; set;  }
    public int PostId { get; set; }
    public int CommentId { get; set; }


    public static Comment GetCommentDetails(int boardId, int postId, int CommentId)
    {
      var apiCallTask = ApiCommentHelper.GetCommentDetails(boardId, postId, CommentId);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Comment comment = JsonConvert.DeserializeObject<Comment>(jsonResponse.ToString());

      return comment;
    }
    public static void CreateComment(int boardId, int postId, Comment comment)
    {
      string jsonComment = JsonConvert.SerializeObject(comment);
      var apiCallTask = ApiCommentHelper.CreateComment(boardId, postId, jsonComment);
    }

    public static void PutComment(int boardId, int postId, Comment comment)
    {
      string jsonComment = JsonConvert.SerializeObject(comment);
      var apiCallTask = ApiCommentHelper.PutComment(boardId, postId, comment.CommentId, jsonComment);
    }

    public static void DeleteComment(int boardId, int postId, int commentId)
    {
      var apiCallTask = ApiCommentHelper.DeleteComment(boardId, postId, commentId);
    }

    // public static void UpVote(int boardId, int postId, int commentId)
    // {
    //   var apiCallTask = ApiCommentHelper.UpVote(boardId, postId, commentId);
    // }
    // public static void DownVote(int boardId, int postId, int commentId)
    // {
    //   var apiCallTask = ApiCommentHelper.DownVote(postId, commentId);
    // }
  }
}
   

CatBoardInterface/Controllers/BoardsController.cs
using CatBoardInterface.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CatBoardInterface.Controllers
{
  public class BoardsController : Controller
  {
    public IActionResult Index()
    {
      var allBoards = Board.GetBoards();
      return View(allBoards);
    }

    public ActionResult Details(int id)
    {
      var thisBoard = Board.GetDetails(id);
      var postsList = thisBoard.Posts.OrderByDescending(post => post.score);
      ViewBag.OrderedPosts = postsList;
      return View(thisBoard);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Board board)
    {
      Board.Post(board);
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisBoard = Board.GetDetails(id);
      return View(thisBoard);
    }

    [HttpPost]
    public ActionResult Edit(Board board)
    {
      Board.Put(board);
      return RedirectToAction("Details", new { id = board.BoardId });
    }

    public ActionResult Delete(int id)
    {
      var thisBoard = Board.GetDetails(id);
      return View(thisBoard);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Board.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

CatBoardInterface/Controllers/CommentsController.cs
using System.Reflection.PortableExecutable;
using CatBoardInterface.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CatBoardInterface.Controllers
{
  public class CommentsController : Controller
  {

    public ActionResult CommentDetails(int boardId, int postId, int commentId)
    {
      var thisComment = Comment.GetCommentDetails(boardId, postId, commentId);
      return View(thisComment);
    }


    public ActionResult Create(int boardId, int postId)
    {
      ViewBag.boardId = boardId;
      ViewBag.postId = postId;
      return View();
    }
    [HttpPost]
    public ActionResult Create(int boardId, int postId, Comment comment)
    {
      Comment.CreateComment(boardId, postId, comment);
      return RedirectToAction("Details", "Posts", new { boardId = boardId, postId = postId });
    }
    public ActionResult Edit(int boardId, int postId, int commentId)
    {
      ViewBag.BoardId = boardId;
      ViewBag.postId = postId;
      var thisComment = Comment.GetCommentDetails(boardId, postId, commentId);
      return View(thisComment);
    }

    [HttpPost]
    public ActionResult Edit(int boardId, int postId, Comment comment)
    {
      Comment.PutComment(boardId, postId, comment);
      return RedirectToAction("Details", "Posts", new { boardId = boardId, postId = postId });
    }

    public ActionResult Delete(int boardId, int postId, int commentId)
    {
      var thisComment = Comment.GetCommentDetails(boardId, postId, commentId);
      return View(thisComment);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int boardId, int postId, int commentId)
    {
      Comment.DeleteComment(boardId, postId, commentId);
    return RedirectToAction("Details", "Posts", new { boardId = boardId, postId = postId });
    }

  }
}
                              

CatBoardInterface/Views/Comments/Create.cshtml
@model CatBoardInterface.Models.Comment

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1 class="text-center">Add Comment</h1>
    <p> view bag for board Id = @ViewBag.boardId </p>
    <p> view bag for post Id= @ViewBag.postId </p>
    @using (Html.BeginForm("Create", "Comments"))
    {
      <input type="hidden" name="boardId" value="@ViewBag.boardId">
      <input type="hidden" name="postId" value="@ViewBag.postId">

      <div class="form-group">
        <p>Comment</p>
        @Html.TextBoxFor(model => model.Body, new {@class="form-control"})
      </div>

      <button type="submit" class="btn btn-info btn-block"> Add a Comment </button>
    }
  </div>
</div> 

CatBoardInterface/Views/Comments/Details.cshtml
<h1>Details</h1>
<div class="post-img">
  <img src="@Model.ImageSource" alt="post picture">
</div>
<div> @Model.Title </div>
<div> @Model.Body </div>
<div> @Model.score </div>
<div class="col-sm-1 text-center">
    @using (Html.BeginForm("Comment", "Posts"))
    {
      <input id="postId" name="postId" type="hidden" value="@Model.PostId">
      <input id="boardId" name="boardId" type="hidden" value="@Model.BoardId">
      <input id="viewId" name="viewId" type="hidden" value="0">
      <button type="submit" value="UpVote" class="btn btn-success btn-sm"><i class="fas fa-caret-square-up"></i></button>
    }

</div>

<hr>

@Html.ActionLink("Edit", "Edit", "Posts", new {boardId = Model.BoardId, postId = Model.PostId }, new {@class="btn btn-info"})
@Html.ActionLink("Delete", "Delete", "Posts", new {boardId = Model.BoardId, postId = Model.PostId }, new {@class="btn btn-danger"})
@Html.ActionLink("Back", "Details", "Boards", new {id = Model.BoardId}, new {@class="btn btn-warning"})